In [2]:
import numpy as np

In [3]:
a=np.arange(2,15)

In [4]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
a=np.linspace(0,20,10)

In [6]:
a

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [7]:
#random
r=np.random.rand()

In [8]:
r

0.5687918988767621

In [9]:
#thisisstandarddistributiom

In [10]:
r=np.random.rand(6)

In [11]:
r

array([0.36657053, 0.68773202, 0.68077357, 0.98942434, 0.45349742,
       0.15990239])

In [12]:
r=np.random.randint(3,10)

In [13]:
r

8

In [14]:
r=np.random.randint(3,10,3)

In [15]:
r

array([9, 7, 3])

In [16]:
r=np.random.randint(3,10,(3,3))

In [17]:
r

array([[9, 4, 9],
       [3, 5, 4],
       [7, 8, 7]])

In [36]:
#random
np.random.seed(101)
r=np.random.randint(0,10,(5,5))
r

array([[1, 6, 7, 9, 8],
       [4, 8, 5, 0, 5],
       [8, 1, 3, 8, 3],
       [3, 2, 8, 9, 3],
       [7, 0, 9, 7, 9]])

In [19]:
r.sum()

48

In [20]:
r.sum(axis=0)

array([18, 19, 11])

In [21]:
r.size

9

In [22]:
r.shape

(3, 3)

In [23]:
len(r)
#givesnumofelementsin1column

3

In [24]:
r.itemsize

4

In [25]:
r.dtype

dtype('int32')

TypeError: rand() got an unexpected keyword argument 'dtype'

In [34]:
jacker=np.array([1,1,23,444])

In [35]:
jacker

array([  1,   1,  23, 444])

In [36]:
om=np.array([[1,7],[9,4]])

In [37]:
om

array([[1, 7],
       [9, 4]])

In [54]:
jacker=np.arange(1,20)

In [55]:
jacker

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
a=np.linspace(0,20,30)

In [53]:
a

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

In [56]:
type(a)

numpy.ndarray

In [57]:
a.shape

(30,)

In [58]:
om.shape

(2, 2)

In [59]:
jacker.shape

(19,)

In [61]:
type(jacker)

numpy.ndarray