In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [3]:
a.ndim

1

In [4]:
type(a.shape)

tuple

In [7]:
a.shape

(9,)

In [5]:
b=a.reshape(3,3)

In [6]:
b.shape

(3, 3)

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pwd

'C:\\Users\\STUDENT\\Documents'

In [8]:
b.ndim

2

In [9]:
a.ndim

1

In [26]:
c=[1,2,3,4,5,6,7,8,9,10]

In [27]:
type(c)

list

In [28]:
b=c.reshape(3,3)

AttributeError: 'list' object has no attribute 'reshape'

In [29]:
cc=np.array(c)

In [30]:
b=cc.reshape(3,3)

ValueError: total size of new array must be unchanged

In [14]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
b=cc.reshape(-100,3)

In [16]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
b=cc.reshape(-50,1)

In [18]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
b.ndim

2

In [20]:
a.ndim

1

In [31]:
b=cc.reshape(2,-50)

In [32]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
bb=np.resize(a,(2,6))

In [34]:
bb

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [35]:
a_z=np.zeros([3,3])

In [36]:
a_z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
a_z.dtype

dtype('float64')

In [38]:
a_o=np.ones([3,3])

In [39]:
a_o

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [40]:
a_o=np.ones([4,4])

In [41]:
print("value of a_z \n {} \n value of a_o \n {}".format(a_z,a_o))

value of a_z 
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 
 value of a_o 
 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [42]:
#thiswasonesndzerosfunction

In [43]:
a_i=np.eye(3)

In [44]:
print(a_i)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
