In [3]:
from sklearn import datasets
import numpy as np

In [4]:
mydata=datasets.load_iris()

In [5]:
mydata.data.shape

(150, 4)

In [7]:
mydata.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [4]:
mydata.target_names

array(['setosa', 'versicolor', 'virginica'], 
      dtype='<U10')

In [9]:
mydata.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
mydata.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
#input and out separate
X_input=mydata.data
Y_target=mydata.target

In [8]:
X_input

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [9]:
Y_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
X_input[0,:]

array([ 5.1,  3.5,  1.4,  0.2])

In [11]:
Y_target[0]

0

In [12]:
Y_target[-1]

2

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
a,b,c,d=train_test_split(X_input,Y_target,test_size=.10)

NameError: name 'X_input' is not defined

In [17]:
a.shape

(135, 4)

In [18]:
a

array([[ 6.5,  3. ,  5.2,  2. ],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 5.2,  2.7,  3.9,  1.4],
       [ 6.3,  2.8,  5.1,  1.5],
       [ 5.1,  3.8,  1.6,  0.2],
       [ 6.6,  3. ,  4.4,  1.4],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 7.9,  3.8,  6.4,  2. ],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 7.7,  2.6,  6.9,  2.3],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 6.5,  3. ,  5.8,  2.2],
       [ 5.3,  3.7,  1.5,  0.2],
       [ 6.9,  3.1,  4.9,  1.5],
       [ 5.7,  2.8,  4.1,  1.3],
       [ 6.3,  2.5,  4.9,  1.5],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 6.5,  3.2,  5.1,  2. ],
       [ 4.8,  3. ,  1.4,  0.3],
       [ 6.7,  3.1,  5.6,  2.4],
       [ 5.6,  2.8,  4.9,  2. ],
       [ 5

In [19]:
c

array([1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 2,
       2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 2, 1, 2, 1, 2, 0, 0,
       1, 1, 1, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 2, 1, 2, 2,
       2, 2, 2, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 1, 2, 0, 0, 1, 2, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 2, 0,
       0, 1, 0, 1, 0, 2, 2, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 0, 0, 0])

In [20]:
d

array([1, 1, 1, 2, 2, 1, 0, 1, 2, 1, 1, 2, 1, 0, 0])

In [43]:
a,b,c,d=train_test_split(X_input,Y_target,test_size=.30,random_state=101)

In [44]:
a

array([[ 7.7,  2.8,  6.7,  2. ],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 5.7,  2.6,  3.5,  1. ],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 7.2,  3. ,  5.8,  1.6],
       [ 6.4,  3.1,  5.5,  1.8],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 5.1,  3.4,  1.5,  0.2],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 4

In [45]:
b

array([[ 5.8,  2.7,  3.9,  1.2],
       [ 5.6,  3. ,  4.1,  1.3],
       [ 6.7,  3. ,  5. ,  1.7],
       [ 5.2,  2.7,  3.9,  1.4],
       [ 5.6,  2.5,  3.9,  1.1],
       [ 6.8,  2.8,  4.8,  1.4],
       [ 5.8,  2.7,  5.1,  1.9],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.5,  2.4,  3.7,  1. ],
       [ 6.5,  3. ,  5.5,  1.8],
       [ 5.5,  2.5,  4. ,  1.3],
       [ 5.9,  3. ,  5.1,  1.8],
       [ 6.3,  2.5,  4.9,  1.5],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 7.2,  3.2,  6. ,  1.8],
       [ 6. ,  2.2,  5. ,  1.5],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 5. ,  3.3,  1.4,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.7,  2.5,  5. ,  2. ],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 6.4,  2.8,  5.6,  2.1],
       [ 5.4,  3. ,  4.5,  1.5],
       [ 6.8,  3.2,  5.9,  2.3],
       [ 6. ,  2.2,  4. ,  1. ],
       [ 5.6,  2.9,  3.6,  1.3],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 6

In [46]:
a

array([[ 7.7,  2.8,  6.7,  2. ],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 6.8,  3. ,  5.5,  2.1],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 6.9,  3.2,  5.7,  2.3],
       [ 6.7,  3.1,  4.4,  1.4],
       [ 4.9,  2.5,  4.5,  1.7],
       [ 7. ,  3.2,  4.7,  1.4],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 5.7,  2.6,  3.5,  1. ],
       [ 5.9,  3. ,  4.2,  1.5],
       [ 7.7,  3. ,  6.1,  2.3],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 6.2,  2.2,  4.5,  1.5],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 7.6,  3. ,  6.6,  2.1],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 6. ,  3. ,  4.8,  1.8],
       [ 6.1,  3. ,  4.9,  1.8],
       [ 4.6,  3.2,  1.4,  0.2],
       [ 7.2,  3. ,  5.8,  1.6],
       [ 6.4,  3.1,  5.5,  1.8],
       [ 6.7,  3.3,  5.7,  2.5],
       [ 6.2,  2.8,  4.8,  1.8],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 5.1,  3.4,  1.5,  0.2],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5. ,  3.5,  1.6,  0.6],
       [ 4

In [47]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
teacher=KNeighborsClassifier()

In [49]:
learner=teacher.fit(a,c)

In [50]:
Ya=d
Yp=learner.predict(b)

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
acc=accuracy_score(Ya,Yp)*100

In [53]:
acc

31.111111111111111