In [22]:
import numpy as np

In [23]:
X=np.array([1,2,3,4])

In [24]:
X

array([1, 2, 3, 4])

In [25]:
Y=np.array([6,5,7,10])

In [26]:
Y

array([ 6,  5,  7, 10])

In [27]:
X=X.reshape(-1,1)

In [28]:
X

array([[1],
       [2],
       [3],
       [4]])

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
teacher=LinearRegression()

In [31]:
learner=teacher.fit(X,Y)

In [32]:
learner.predict([[1]])

array([ 4.9])

In [33]:
learner.predict([[3]])

array([ 7.7])

In [34]:
learner.coef_

array([ 1.4])

In [35]:
learner.intercept_

3.5000000000000013

In [36]:
learner.predict([[4]])

array([ 9.1])

In [37]:
Z=np.array([4,8,2,9])

In [38]:
learner=teacher.fit(X,Z)

In [39]:
learner.predict([[1]])

array([ 4.4])

In [40]:
learner.predict([[3]])

array([ 6.2])

In [43]:
learner.predict([[2]])

array([ 5.3])

In [44]:
learner.predict([[1]])

array([ 4.4])

In [45]:
learner.intercept_

3.5

In [46]:
learner.coef_

array([ 0.9])

In [47]:
learner.predict([[1]])

array([ 4.4])

In [53]:
X=np.array([1,2,3,4])

In [54]:
X

array([1, 2, 3, 4])

In [55]:
learner.predict([[1]])

array([ 4.4])

In [56]:
Y=np.array([6,5,7,10])

In [57]:
learner.predict([[1]])

array([ 4.4])

In [ ]:
`