In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5])

In [5]:
x

array([1, 2, 3, 4, 5])

In [6]:
x.shape

(5,)

In [12]:
X=x.reshape(-1,1)

In [13]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [14]:
Y=np.array([1,3,2,3,5])

In [15]:
Y


array([1, 3, 2, 3, 5])

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
teacher=LinearRegression()

In [19]:
learner=teacher.fit(X,Y)

In [21]:
learner.predict([[1]])

array([ 1.2])

In [22]:
learner.coef_

array([ 0.8])

In [23]:
learner.intercept_

0.39999999999999991